---
- name: playbook with complex variables
  hosts: all
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        uid: "{{ user_id }}"
        comment: "{{ user_comment }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
